name: Update Packages

on:
  schedule:
    - cron: '5 12 * * *' # 06:05 CST (UTC-6)
  workflow_dispatch:

jobs:
  update:
    uses: mpimedia/mpi-application-workflows/.github/workflows/update-packages.yml@main
    secrets: inherit
