name: Update Gems

on:
  schedule:
    - cron: '0 12 * * *' # 06:00 CST (UTC-6)
  workflow_dispatch:

jobs:
  update:
    uses: mpimedia/mpi-application-workflows/.github/workflows/update-gems.yml@main
    secrets: inherit
